/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewLocationIdRouteImport } from './routes/view.$locationId'
import { Route as LocationLocationIdRouteImport } from './routes/location.$locationId'
import { Route as LocationRouteImport } from './routes/location.'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewLocationIdRoute = ViewLocationIdRouteImport.update({
  id: '/view/$locationId',
  path: '/view/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLocationIdRoute = LocationLocationIdRouteImport.update({
  id: '/location/$locationId',
  path: '/location/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/location/': typeof LocationRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/view/$locationId': typeof ViewLocationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/location': typeof LocationRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/view/$locationId': typeof ViewLocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/location/': typeof LocationRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/view/$locationId': typeof ViewLocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/explore'
    | '/login'
    | '/location/'
    | '/location/$locationId'
    | '/view/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/explore'
    | '/login'
    | '/location'
    | '/location/$locationId'
    | '/view/$locationId'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/explore'
    | '/login'
    | '/location/'
    | '/location/$locationId'
    | '/view/$locationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  LocationRoute: typeof LocationRoute
  LocationLocationIdRoute: typeof LocationLocationIdRoute
  ViewLocationIdRoute: typeof ViewLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$locationId': {
      id: '/view/$locationId'
      path: '/view/$locationId'
      fullPath: '/view/$locationId'
      preLoaderRoute: typeof ViewLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/location'
      fullPath: '/location/'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  LocationRoute: LocationRoute,
  LocationLocationIdRoute: LocationLocationIdRoute,
  ViewLocationIdRoute: ViewLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
